//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Materialize.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Doctors
    {
        public long DoctorId { get; set; }
        public string CRM { get; set; }
        public string FullName { get; set; }
        public string Adress { get; set; }
        public string Neighborhood { get; set; }
        public string Email { get; set; }
        public bool WorksWithCovenant { get; set; }
        public bool HasClinic { get; set; }
        public string Website { get; set; }
        public long CityId { get; set; }
        public long SpecialtyId { get; set; }
    
        public virtual Cities Cities { get; set; }
        public virtual Specialties Specialties { get; set; }
    }
}
